# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 483043409bb79df2fb11e19de17f548759bd57b674fcc43ef5af93fb3d5802ad6de304effd1a56eb2302e95b8fd41524288b6e4a53c88e8aaab292fd606d2069

test:
  secret_key_base: cf68e7129227fd4583765eac40cda1f28fc7383fe88c2683f480c081564ea77e2b47eaeb3265f1b54068aede618004f026d796a184588c452e1c5dcb456d6193

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
